spring.datasource.url=jdbc:sqlserver://alunos-db.database.windows.net:1433;database=alunos_db
spring.datasource.username=userdb
spring.datasource.password=EniEssi#1990
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
